{"implements":["ghidra.util.ErrorDisplay"],"javadoc":"An error display wrapper that allows us to fail tests when errors are encountered.  This is \n a way for us to fail for exceptions that come from client code, but are handled by the \n error display service, while running tests.","static":false,"extends":"java.lang.Object","methods":[{"javadoc":"","static":false,"name":"<init>","comment":"","params":[],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}},{"javadoc":"","static":false,"name":"setErrorDisplayDelegate","comment":"","params":[{"type_long":"ghidra.util.ErrorDisplay","name":"delegate","comment":"","type_short":"ErrorDisplay"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}},{"javadoc":"","static":false,"name":"displayInfoMessage","comment":"","params":[{"type_long":"ghidra.util.ErrorLogger","name":"errorLogger","comment":"","type_short":"ErrorLogger"},{"type_long":"java.lang.Object","name":"originator","comment":"","type_short":"Object"},{"type_long":"java.awt.Component","name":"parent","comment":"","type_short":"Component"},{"type_long":"java.lang.String","name":"title","comment":"","type_short":"String"},{"type_long":"java.lang.Object","name":"message","comment":"","type_short":"Object"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}},{"javadoc":"","static":false,"name":"displayErrorMessage","comment":"","params":[{"type_long":"ghidra.util.ErrorLogger","name":"errorLogger","comment":"","type_short":"ErrorLogger"},{"type_long":"java.lang.Object","name":"originator","comment":"","type_short":"Object"},{"type_long":"java.awt.Component","name":"parent","comment":"","type_short":"Component"},{"type_long":"java.lang.String","name":"title","comment":"","type_short":"String"},{"type_long":"java.lang.Object","name":"message","comment":"","type_short":"Object"},{"type_long":"java.lang.Throwable","name":"throwable","comment":"","type_short":"Throwable"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}},{"javadoc":"","static":false,"name":"displayWarningMessage","comment":"","params":[{"type_long":"ghidra.util.ErrorLogger","name":"errorLogger","comment":"","type_short":"ErrorLogger"},{"type_long":"java.lang.Object","name":"originator","comment":"","type_short":"Object"},{"type_long":"java.awt.Component","name":"parent","comment":"","type_short":"Component"},{"type_long":"java.lang.String","name":"title","comment":"","type_short":"String"},{"type_long":"java.lang.Object","name":"message","comment":"","type_short":"Object"},{"type_long":"java.lang.Throwable","name":"throwable","comment":"","type_short":"Throwable"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}}],"name":"TestFailingErrorDisplayWrapper","comment":"An error display wrapper that allows us to fail tests when errors are encountered.  This is \n a way for us to fail for exceptions that come from client code, but are handled by the \n error display service, while running tests.","fields":[{"type_long":"ghidra.util.ErrorDisplay","javadoc":"","static":false,"name":"delegate","comment":"","type_short":"ErrorDisplay","constant_value":null}]}
